version: "3.8"

services:
  jupyter-spark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./datos_dane:/home/jovyan/datos_dane
      - ./resultados:/home/jovyan/resultados
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''
